@startuml

class Game
class Main
class TextUI
class Player
class Questions
class GameEnd
class FileIO
class QuestionsDB

Game *-- Main
Main *-- TextUI
TextUI *-- Player
Player *-- Questions
Questions *-- QuestionsDB
Player *-- FileIO
FileIO *-- Questions
Questions *-- GameEnd


Game : + Main main;
Game : + void main()

Main : + static void main()

TextUI : + Scanner scanner;
TextUI : + void clearTheConsole()
TextUI : + void startGame()
TextUI : + void chooseDrinkOption()
TextUI : + void choosePlayerStatus()

QuestionsDB : - Connection connection;
QuestionsDB : - String url;
QuestionsDB : - String userName;
QuestionsDB : - String userPassword;
QuestionsDB : + ArrayList<Questions> questions;

Player : - String name;
Player : - int password;
Player : + boolean isOver18;
Player : + Player()
Player : + String getName()
Player : + void setName()
Player : + int getPassword()
Player : + void setPassword()
Player : + String toString()

FileIO : + ArrayList<Player> players;
FileIO : + ArrayList<Score> scores;
FileIO : + File file;
FileIO : + void registerPlayer()
FileIO : + boolean checkUser()
FileIO : + boolean checkUserSignUp()
FileIO : + void registerScore()

Questions : + void getDrinkOption()
Questions : + void getPlayerStatus()
Questions : + void getScore()

GameEnd : + String displayHighScore()
GameEnd : + String checkWhoWon()


@enduml